spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/majestic_cup
      database: majestic_cup
#      username: yassir
#      password: User_Password
      authentication-database: admin

logging:
  level:
    org.springframework.security: DEBUG


